Feature/controller handler
kroshu/kroshu_ros2_core pull request #13
Opened 2023-05-23 13:42 UTC by altex111

2023-05-23 14:08 UTC, Svastits commented
General commennts:
 - there are quite a lot of typos in the comments, I have not pointed them out one by one, please re-read them
 - please use the naming conventions for funtion names and enums:
   - functions: functionName, e.g. updateControllerName (snake_case (e.g. get_active_controllers) can also be ok, but try to stick to this convention)
   - enums: EnumName, e.g. ControllerType
 - CI should be green

2023-05-23 14:28 UTC, Svastits requested changes

2023-05-23 14:28 UTC, Svastits commented on src/ControllerHandler.cpp
> +    throw std::logic_error("Not implemented exepton");
typo

2023-05-23 14:28 UTC, Svastits commented on src/ControllerHandler.cpp
> +std::pair<std::vector<std::string>,
Is this function necessary? by deactivation you can just call the get_active_controllers, and fill the request with the result, the activate_controllers will be always empty in this case

2023-05-23 14:28 UTC, Svastits commented on src/ControllerHandler.cpp
> +    throw std::logic_error("Not implemented exepton");
msg: UNSPECIFIED_CONTROL_MODE is not a valid control mode

2023-05-23 14:28 UTC, Svastits commented on src/ControllerHandler.cpp
> +  }
IMO you should delete the activate_controllers_ vector

2023-05-23 14:28 UTC, Svastits commented on src/ControllerHandler.cpp
> +  }
deactivate_controllers_ should also be cleared

2023-05-23 14:28 UTC, Svastits commented on src/ControllerHandler.cpp
> +  }
This should not happen, but you might want to check if find() was not unsuccesful

2023-05-23 14:28 UTC, Svastits commented on include/kroshu_ros2_core/ControllerHandler.hpp
> +    std::vector<std::string>> Get_activate_deactivate_controllers(
Only brainstorming for the function name:
calculateControlModeSwitch ?
handleControlModeSwitch ?

2023-05-23 14:56 UTC, VX792 requested changes

2023-05-23 14:56 UTC, VX792 commented on include/kroshu_ros2_core/controller_handler.hpp
> +  static constexpr int NORMAL_CONTROLLER_POS = 0;
what is a 'normal' controller? I think you could use a more descriptive name here

2023-05-23 14:56 UTC, VX792 commented on src/controller_handler.cpp
> +  control_mode_map_.emplace(
I think it would look a lot nicer to create something like 
```
control_mode_map{
{ something1,  std::vector<std::string>(something) },
{ something2,  std::vector<std::string>(something) },
...
};
```

And I'm sure there are even better solutions than this, but for now this is probably fine.

2023-05-23 14:56 UTC, VX792 commented on src/controller_handler.cpp
> +  }
this could be done with a more efficient algorithm than this one with O(n^2) time complexity, although it doesn't really matter in this case since both vectors will be small.

2023-05-23 14:56 UTC, VX792 commented on src/controller_handler.cpp
> +  return std::make_pair(activate_controllers_, deactivate_controllers_);
the name here is a bit misleading, since you're getting the deactivated controllers, and erasing the active controllers. Also, is it necessary to return the activate_controllers_ vector if you know that it will be empty?

2023-05-23 14:56 UTC, VX792 commented on src/controller_handler.cpp
> +        break;
breaking early is bad if the controller names are not unique. Not sure if this can happen though

2023-05-23 14:56 UTC, VX792 commented on src/controller_handler.cpp
> +      control_mode_map_.at(control_mode::POSITION_CONTROL_MODE).at(NORMAL_CONTROLLER_POS) =
Is there really no better way of doing this? There's a lot of repetition here

2023-05-23 14:56 UTC, VX792 commented on src/controller_handler.cpp
> +      active_controllers_.erase(active_controllers_.find(controller));
cool, this is exactly how sets should be used!

2023-05-23 14:56 UTC, VX792 commented on src/controller_handler.cpp
> +  return std::vector<std::string>(active_controllers_.begin(), active_controllers_.end());
is this needed? you can simply use the set's iterator in the algorithm. And in the other function it's also possible to return a set instead

2023-05-23 18:32 UTC, VX792 requested changes
I've left another batch of comments, since for some reason github showed the previous ones as outdated. Hopefully I did it right this time!

2023-05-23 18:32 UTC, VX792 commented on include/kroshu_ros2_core/ControllerHandler.hpp
> +  static constexpr int NORMAL_CONTROLLER_POS = 0;
The name "normal controller" is not very descriptive. Can this be changed to something else?

2023-05-23 18:32 UTC, VX792 commented on src/ControllerHandler.cpp
> +  control_mode_map_.emplace(
I think it would look a lot nicer to create something like 
```
control_mode_map{
{ something1,  std::vector<std::string>(something) },
{ something2,  std::vector<std::string>(something) },
...
};
```

And I'm sure there are even better solutions than this, but for now this is probably fine.

2023-05-23 18:32 UTC, VX792 commented on src/ControllerHandler.cpp
> +    case Controller_type::POSITION_CONTROLLER_TYPE:
we should definitely do something about this, maybe in a follow-up PR

2023-05-23 18:32 UTC, VX792 commented on src/ControllerHandler.cpp
> +    }
This is a O(n^2) complexity algorithm. Since the vector's size will be quite small, this doesn't matter, but would be nice to improve this.

Also, that early break is problematic if there are duplicates in the vectors. Can that even happen?

2023-05-23 18:32 UTC, VX792 commented on src/ControllerHandler.cpp
> +  return std::vector<std::string>(active_controllers_.begin(), active_controllers_.end());
is this function needed? it's used only in the algorithm, which could simply use the set's iterator without having to convert it to a vector

2023-05-23 18:32 UTC, VX792 commented on src/ControllerHandler.cpp
> +  return std::make_pair(activate_controllers_, deactivate_controllers_);
can this return the deactivate_controllers vector / set? the activate_controllers array will be always empty, so it's pointless to return it.

2023-05-25 14:26 UTC, altex111 commented on include/kroshu_ros2_core/ControllerHandler.hpp
> +  typedef enum   //controller_type
Done

2023-05-25 14:29 UTC, altex111 commented on include/kroshu_ros2_core/ControllerHandler.hpp
> +  static constexpr int NORMAL_CONTROLLER_POS = 0;
Changed to standard like above.

2023-05-25 14:32 UTC, altex111 commented on include/kroshu_ros2_core/ControllerHandler.hpp
> +    std::vector<std::string>> Get_activate_deactivate_controllers(
Modified to GetConrollersForSwitch, How do you like that?

2023-05-25 14:43 UTC, altex111 commented on src/ControllerHandler.cpp
> +    }
I beleve everithing can only be only once in them

2023-05-25 14:46 UTC, altex111 commented on src/ControllerHandler.cpp
> +  return std::vector<std::string>(active_controllers_.begin(), active_controllers_.end());
used twice, and spoke with @Svastits  about it, It is needed

2023-05-26 08:57 UTC, Svastits commented on include/kroshu_ros2_core/ControllerHandler.hpp
> +    std::vector<std::string>> Get_activate_deactivate_controllers(
fine :)

2023-05-26 08:58 UTC, VX792 requested changes

2023-05-26 08:58 UTC, VX792 commented on src/ControllerHandler.cpp
> +    }
This is still O(n^3). My bad for saying this is n^2, missed that we're comparing strings. 

It's true that we don't gain much in this specific case by optimizing this, but when we're already handwaving away so many things, adding a brute-force algorithm just like that tells the reader that we didn't care enough to get it right. And of course, they'd be right. Especially in this scenario, where the optimal solution is pretty concise.

If we're going to write the code in C++, it would make sense to always use the most efficient algorithm, because it doesn't matter how many micro-optimizations we're doing in the hot path, (like avoiding heap allocations or I/O handling), any performance gains gotten by these can easily be nullified by using a garbage algorithm.

2023-05-26 08:58 UTC, VX792 commented on src/ControllerHandler.cpp
> +  for (auto && controller : fixed_controllers_) {
why can't the control_mode_map_ include the fixed controllers too? One less vector to keep track of

2023-05-26 08:58 UTC, VX792 commented on src/ControllerHandler.cpp
> +  switch (controller_type) {
This is looking worse with each merge. A vector is not a good data structure for this task, no matter how many indices we're renaming. I don't want to make this a blocker for the PR, but this should be fixed in the follow-up.

2023-05-26 09:09 UTC, VX792 commented on src/ControllerHandler.cpp
> +        controller_name;
why the same controller for both?

2023-05-26 14:52 UTC, altex111 commented on src/ControllerHandler.cpp
> +  control_mode_map_.emplace(
implemented

2023-05-26 14:56 UTC, altex111 commented on src/ControllerHandler.cpp
> +  for (auto && controller : fixed_controllers_) {
Logicaly those are not controllers, acprding to Svastits

2023-05-26 15:07 UTC, altex111 commented on src/ControllerHandler.cpp
> +  }
It not just shouldn't happen, it can not happen because the deactivate controllers is filled with the active controllers every time.
Another situation is when the deactivate controllers are empty, then the function will do nothing.

2023-05-26 15:10 UTC, altex111 commented on src/ControllerHandler.cpp
> +    }
maybe if we use sets insted of vectors, they will be oriented in abc order, and we can use that in our advantage, a have no other idea

2023-05-26 18:55 UTC, VX792 commented on src/ControllerHandler.cpp
> +    }
Yes, that's right! You can also use std::sort on the vectors, and since the better sorting algorithms have a time complexity of O(nlogn), it's already an improvement. Then you just have to iterate through the sorted array and do stuff.

There's an even better approach for this, and I think you can figure it out on your own too, but we can also talk about it next week.

If either of these two is implemented then I'll happily approve the PR

2023-05-30 10:03 UTC, Svastits commented on src/ControllerHandler.cpp
> +  }
I can accept this answer :)

2023-05-30 10:07 UTC, Svastits commented on include/kroshu_ros2_core/ControllerHandler.hpp
> + *  - Calculate_activate_deactivate_controllers() or Get_active_controllers_on_deactivation()
please update this with the new names

2023-05-31 08:15 UTC, Svastits commented on include/kroshu_ros2_core/ControllerHandler.hpp
> +    std::string impadence_cotroller;
typo: impedance_controller

2023-05-31 08:20 UTC, Svastits commented on include/kroshu_ros2_core/ControllerHandler.hpp
> +  static constexpr int STANDARD_CONTROLLER_POS = 0;
I think now these are not used

2023-05-31 08:22 UTC, Svastits commented on include/kroshu_ros2_core/ControllerHandler.hpp
> +  /**
this is also no longer necessary

2023-05-31 14:27 UTC, VX792 requested changes

2023-05-31 14:27 UTC, VX792 commented on src/ControllerHandler.cpp
> +      deactivate_controllers_.erase(activate_controllers_it);
wait, there's no way this should work. You're trying to erase an element from another container's iterator from the deactivate_controllers set.

2023-05-31 14:27 UTC, VX792 commented on src/ControllerHandler.cpp
> +      --activate_controllers_it;
this looks fishy too, since the set's iterator becomes invalid after erasing an element. This might work for std::vector, but might not for a set.

2023-05-31 15:46 UTC, altex111 commented on src/ControllerHandler.cpp
> +      deactivate_controllers_.erase(activate_controllers_it);
corrected, deleting with the controllers name

2023-05-31 15:59 UTC, altex111 commented on src/ControllerHandler.cpp
> +std::vector<std::string> ControllerHandler::GetControllersForDeactivation()
yes, in the on_deactivate function

2023-06-01 06:48 UTC, VX792 commented on src/ControllerHandler.cpp
> +  return ret_val;
why not return true here, and return false in the default branch? That variable is not needed

2023-06-01 07:43 UTC, Svastits approved these changes

2023-06-01 07:57 UTC, merged