Feature/base node
kroshu/kroshu_ros2_core pull request #4
Opened 2022-05-16 14:11 UTC by Svastits

2022-05-17 05:49 UTC, Svastits commented on src/ParameterHandler.cpp
> +      printf("Invalid parameter name\n");
When used properly, we should not reach this, but perhaps better to keep additional check to filter improper use

2022-05-18 08:04 UTC, kovacsge11 requested changes
See suggested changes for removing "friend" keyword, add remark as comment.

2022-05-18 08:04 UTC, kovacsge11 commented on src/ParameterHandler.cpp
> +      printf("Invalid parameter name\n");
Add your remark as comment:

```suggestion
    // When used properly, we should not reach this, but better to keep additional check to filter improper use
    if (found_param_it == params_.end()) {
      printf("Invalid parameter name\n");
```

2022-05-18 09:37 UTC, kovacsge11 approved these changes

2022-05-18 09:37 UTC, merged